### ISSUE TITLE
Cosas Pendientes

### ISSUE THREAD

**Issue by lucasbara** [matiascalvar/medical-hub-pf#127]
- Boton de confirmar turno. **HECHO**
- Navbar modo medico
- Algo que identifique que es medico
- Modal Mercadopago  **HECHO**
- Cuando te registras, mostrar error de que ya estas registrado
- Login, mostrar error cuando ya estas registrado
- Hay que acomodar el nombre de los planes

**Comment by matiascalvar** [comment]
Mejorados los botones de confirmar el turno

**Comment by matiascalvar** [comment]
Hay que acomodar el nombre de los planes

**Comment by matiascalvar** [comment]
Hecho el modal de Mercado Pago
